---
install_dependencies:
  Debian:
    - git
    - build-essential
    - autoconf
    - automake
    - libtool
    - shtool
    - python-six
    - wget
  RedHat:
    - git
    - gcc
    - make
    - autoconf
    - automake
    - libtool
    - shtool
    - python-six
    - wget

ovs_dpdk_lcore_mask: 0x1
ovs_dpdk_pmd_mask: 0x2
ovs_dpdk_socket_mem: "256,0"
