apiVersion: v1
kind: Pod
metadata:
  generateName: testpmd-
#  labels:
#     env: test
spec:
  containers:
  - name: testpmd
    image: dockerfranck/testpmd
    volumeMounts:
    - mountPath: /dev/huge
      name: hugepage-volume
    command: ["/bin/sleep", "infinity"]
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "1"
        memory: '4096Mi'
        hugepages-1Gi: 4Gi
        intel.com/intel_sriov_dpdk_p0: '1'
        intel.com/intel_sriov_dpdk_p1: '1'
      limits:
        cpu: "1"
        memory: '4096Mi'
        hugepages-1Gi: 4Gi
        intel.com/intel_sriov_dpdk_p0: '1'
        intel.com/intel_sriov_dpdk_p1: '1'
  volumes:
  - name: hugepage-volume
    hostPath:
      path: /sys/devices/system/node/node0/hugepages/hugepages-1048576kB
  restartPolicy: Never
  tolerations:
  - key: "cmk"
    operator: "Exists"
    effect: "NoSchedule"
