---
- name: preconfigure target hosts
  import_playbook: infra/infra_setup.yml
- name: provision Kubernetes cluster using kubespray
  import_playbook: k8s/k8s.yml
- name: install Intel BMRA Container Experience Kit features
  import_playbook: intel/bmra_features.yml
